name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]

    steps:
      - 
        uses: actions/checkout@v2

      - 
        name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0 
        with:
          dotnet-version: 7.0.x

      - 
        name: Restore dependencies
        working-directory: ./src/KeepLearning.MVC
        run: dotnet restore

      - 
        name: Build
        working-directory: ./src/KeepLearning.MVC
        run: dotnet build --no-restore

      - 
        name: KeepLearning.Application.IntegrationTests
        working-directory: ./tests/KeepLearning.Application.IntegrationTests
        run: dotnet test

      - 
        name: KeepLearning.Application.UnitTests
        working-directory: ./tests/KeepLearning.Application.UnitTests
        run: dotnet test

      - 
        name: KeepLearning.Infrastructure.UnitTests
        working-directory: ./tests/KeepLearning.Infrastructure.UnitTests
        run: dotnet test

  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/setup-buildx-action@v3

      - name: Push
        uses: docker/build-push-action@v5
        with:
            context: .
            platform: linux/amd64, linux/arm64
            tags: user/app:latest
            secrets: |
                