name: DOCKERHUB

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/setup-buildx-action@v3

      - name: Push
        uses: docker/build-push-action@v5
        with:
            context: .
            platform: linux/amd64, linux/arm64
            tags: user/app:latest
            secrets: |
                